version: '2'
services:

  novnc-jmeter:
    build:
      context: ./infra/novnc-jmeter
      dockerfile: Dockerfile
    hostname: noVNClinux
    cpu_count: 2
    mem_reservation: 2G
    scale: 1
    # CHROME chrash without this. If crashing continue then monitor /dev/shm usage inside of noVNC by 
    # executing 'watch -n 1 "df -h /dev/shm/"' in LXTerminal parallel when you browsing internet with chrome. 
    # https://github.com/fcwu/docker-ubuntu-vnc-desktop/issues/205#issuecomment-782880997
    # https://developers.google.com/web/tools/puppeteer/troubleshooting#tips
    shm_size: 1G
    cap_add:
      #Google Chrome require this: https://github.com/jessfraz/dockerfiles/issues/65
      - SYS_ADMIN
    ports:
      - '443:443'
    volumes:
      - ./:/home/coder/testcase
    environment:
      - SSL_PORT=443
      - USER=coder
      - PASSWORD=coderpw
      - HTTP_PASSWORD=coderpw
      #- RESOLUTION=1920x1080
      #- X11VNC_ARGS=-multiptr

  nginx.default:
    image: nginx