apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  replicas: 3 
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
      - name: jmslave
        image: theprojectaurora/jmeter_cluster:latest
        imagePullPolicy: Always 
        env:
        - name: _JAVA_OPTIONS
          value: -Djava.net.preferIPv4Stack=true 
        ports:
        - containerPort: 1099
        - containerPort: 50000
        command: ["/bin/sh"]
        args: ["-c", "jmeter-server -Dserver.rmi.localport=50000 -Dserver_port=1099 -Jserver.rmi.ssl.disable=true"]
      nodeSelector:
        perf: "true"
      tolerations:
      - operator: Exists     