apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jmeter-grafana
  labels:
    app: jmeter-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-grafana
  serviceName: jmeter-grafana
  template:
    metadata:
      labels:
        app: jmeter-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.5.1
        imagePullPolicy: Always
        volumeMounts:
          - name: grafana-jmeter-storage-staging
            mountPath: /var/lib/grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_USERS_ALLOW_ORG_CREATE
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          # If you're only using the API Server proxy, set this value instead:
          # value: /api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
          value: /
      initContainers:
      - name: init-chown-data
        image: busybox:1.30
        imagePullPolicy: IfNotPresent
        command:
          - chown
          - -R
          - 472:472
          - /var/lib/grafana
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-jmeter-storage-staging
      nodeSelector:
        perf: "true"
      tolerations:
      - operator: Exists     
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: grafana-jmeter-storage-staging
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending