---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: traefik-ingress-controller
  labels:
    app: jmeter-ingress-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jmeter-ingress-lb
  template:
    metadata:
      labels:
        app: jmeter-ingress-lb
        name: jmeter-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: ssl
        secret:
          secretName: traefik-cert
      - name: config
        configMap:
          name: traefik-conf
      containers:
      - image: traefik
        name: traefik-ingress-lb
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/ssl"
          name: "ssl"
        - mountPath: "/config"
          name: "config"
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - --configfile=/config/traefik.toml
        - --kubernetes
        - --logLevel=DEBUG
---
kind: Service
apiVersion: v1
metadata:
  name: traefik
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: jmeter-ingress-lb
