{
 "title": "Jmeter+K8sPrometheus-metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "K8sNodeInstance",
    "label": "K8sNodeInstance",
    "query": {
     "query": "label_values(kubelet_node_name{kubernetes_io_role!=\"master\"}, node)"
    }
   },
   { "name": "Deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "Statefulset", "query": { "query": "label_values(statefulset)" } },
   { "name": "Daemonset", "query": { "query": "label_values(daemonset)" } },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "app",
    "query": "SHOW TAG VALUES FROM \"process\" WITH KEY = \"application\""
   },
   { "name": "granularity", "query": "1m,5m,1h,5s,15s,30s" },
   {
    "name": "retention",
    "query": "SHOW RETENTION POLICIES ON \"jmeterdb\""
   },
   {
    "name": "transaction",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY IN (\"transaction\",\"application\") where application =~ /$app/ and transaction  !~ /all/"
   }
  ]
 },
 "panels": [
  {
   "title": "JMeter - Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JMeter - Active Users",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$granularity" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"startedT\") FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity) fill(null)",
       "select": [
        [
         { "params": [ "meanAT" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" }
       ]
      }
     ]
    },
    {
     "title": "JMeter - Currents hits per Second",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$granularity" ], "type": "time" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"hit\")  / 30 FROM \"$retention\".\"jmeter\" WHERE \"application\" = '$app' AND \"transaction\" = 'all' AND $timeFilter GROUP BY time(30s)",
       "select": [
        [
         { "params": [ "hit" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "JMeter - % Errors",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
     "format": "percentunit",
     "valueName": "total",
     "targets": [
      {
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\")  / sum(\"count\") FROM \"$retention\".\"jmeter\" WHERE \"application\" =~ /$app$/ AND \"transaction\" = 'all' AND $timeFilter",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / sum(\"count\")"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "JMeter - Hits per Second",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Hits",
       "groupBy": [
        { "params": [ "$granularity" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"hit\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity) fill(null)",
       "select": [
        [
         { "params": [ "hit" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" }
       ]
      }
     ]
    },
    {
     "title": "JMeter - Total Hits",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "measurement": "jmeter",
       "query": "SELECT \"hit\" FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND \"statut\" = 'all' AND $timeFilter",
       "select": [
        [
         { "params": [ "hit" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "JMeter - Errors per Second",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Errors",
       "groupBy": [
        { "params": [ "$granularity" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"countError\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity) fill(0)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JMeter - Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "JMeter - Average Response Time",
     "type": "graph",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$granularity" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"avg\") FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity), \"transaction\"",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "JMeter - Transaction Per Second",
     "type": "graph",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"count\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND \"transaction\" <> 'all' AND $timeFilter GROUP BY time($granularity), \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" },
        { "condition": "AND", "key": "transaction", "operator": "<>", "value": "all" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "JMeter - Error Per Second",
     "type": "graph",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"count\")  / 30 FROM \"$retention\".\"jmeter\" WHERE \"application\" =~ /$app$/ AND \"statut\" = 'ko' AND $timeFilter GROUP BY time(30s), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "JMeter - Error detail",
     "type": "graph",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction - $tag_responseCode : $tag_responseMessage",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "responseMessage" ], "type": "tag" },
        { "params": [ "responseCode" ], "type": "tag" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND \"statut\" = 'ko' AND $timeFilter GROUP BY time($granularity), \"responseCode\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/$app$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^0$|^$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/$transaction/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "K8S PODS - Deployment overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8S PODS - Deployment memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{name=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\", pod!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "K8S PODS - Deployment CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "K8S PODS - Unavailable Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) * 100"
      }
     ]
    },
    {
     "title": "K8S PODS - Memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod, kubernetes_io_hostname)",
       "legendFormat": "< real: {{ pod }} @{{ kubernetes_io_hostname }}"
      },
      {
       "expr": "sum ((kube_pod_container_resource_requests_memory_bytes{pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"})) by (pod, node)",
       "legendFormat": "< rqst: {{ pod }} @{{ node }}"
      },
      {
       "expr": "sum ((kube_node_status_allocatable_memory_bytes{node=~\"^$Node$\"})) by (node)",
       "legendFormat": "> avlbl: {{ node }}"
      }
     ]
    },
    {
     "title": "K8S PODS - CPU usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod, kubernetes_io_hostname)",
       "legendFormat": "< real: {{ pod}} @ {{ kubernetes_io_hostname }}"
      },
      {
       "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}) by (pod, node)",
       "legendFormat": "< rqst: {{ pod }} @{{ node }}"
      },
      {
       "expr": "sum ((kube_node_status_allocatable_cpu_cores{node=~\"^$Node$\"})) by (node)",
       "legendFormat": "> avlbl: {{ node }}"
      }
     ]
    },
    {
     "title": "K8S PODS - Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\", pod_name!=\"\"})"
      }
     ]
    },
    {
     "title": "K8S PODS - Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"})"
      }
     ]
    },
    {
     "title": "K8S PODS - Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
      }
     ]
    },
    {
     "title": "K8S PODS - Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 32 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "K8S PODS - Available (cluster)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))"
      }
     ]
    },
    {
     "title": "K8S PODS - Total (cluster)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))",
       "legendFormat": "{{ $Daemonset }}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S PODS - Disk Usage by PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8S PODS - Disk Usage by pvc",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": " (kubelet_volume_stats_used_bytes{kubernetes_io_hostname=~\"^$Node$\", persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"} / kubelet_volume_stats_capacity_bytes{kubernetes_io_hostname=~\"^$Node$\", persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"})",
       "legendFormat": "{{ persistentvolumeclaim }} | {{ kubernetes_io_hostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S PODS - Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8S PODS - All processes network I/O",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod, kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod }}"
      },
      {
       "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S Nodes - Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8S Nodes - 5 minute load avg by node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Load Average" }
     ],
     "targets": [
      {
       "expr": "avg(node_load5) by (kubernetes_node)",
       "legendFormat": "{{kubernetes_node}}"
      }
     ]
    },
    {
     "title": "K8S Nodes - Disk Usage by Node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) by (kubernetes_node)  - sum(node_filesystem_free_bytes{device!=\"rootfs\"}) by (kubernetes_node)) / sum(node_filesystem_size_bytes{device!=\"rootfs\"}) by (kubernetes_node)",
       "legendFormat": "{{ kubernetes_node }}"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage by node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg by (kubernetes_node) ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes  - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes)",
       "legendFormat": "{{kubernetes_node}}"
      }
     ]
    },
    {
     "title": "K8S Nodes - Node CPU Usage ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "cpu usage" }
     ],
     "targets": [
      {
       "expr": "1 - (avg by (kubernetes_node) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
       "legendFormat": "{{kubernetes_node}}"
      }
     ]
    },
    {
     "title": "K8S Nodes - Pods running count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kube_pod_status_phase{}) by (phase)",
       "legendFormat": "{{phase}}"
      },
      {
       "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "K8S Nodes - Top 5 memory intense pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum(container_memory_usage_bytes{image!=\"\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S Nodes - Node - $K8sNodeInstance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "K8sNodeInstance",
   "collapsed": true,
   "panels": [
    {
     "title": "K8S Nodes - System Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(node_load1{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 1m"
      },
      {
       "expr": "avg(node_load5{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 5m"
      },
      {
       "expr": "avg(node_load15{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 15m"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage",
     "type": "singlestat",
     "description": "-/+ buffers/cache",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"}  - node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"}) / node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"})"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory used"
      },
      {
       "expr": "avg(node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "avg(node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory cached"
      },
      {
       "expr": "avg(node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory free"
      }
     ]
    },
    {
     "title": "K8S Nodes - Disk Space Usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"})"
      }
     ]
    },
    {
     "title": "K8S Nodes - Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "written"
      },
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "io time"
      }
     ]
    },
    {
     "title": "K8S Nodes - Network Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(device) (rate(node_network_receive_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "sum (rate(node_network_receive_bytes_total{ikubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "K8S Nodes - Network Transmitted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(device) (rate(node_network_transmit_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "sum (rate(node_network_transmit_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "K8S Nodes - CPU Usage by Pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\", instance=~\"$K8sNodeInstance\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage by Pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (container_memory_usage_bytes{instance=~\"$K8sNodeInstance\", container!=\"POD\", pod!=\"\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S Nodes - Node - $K8sNodeInstance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8S Nodes - System Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(node_load1{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 1m"
      },
      {
       "expr": "avg(node_load5{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 5m"
      },
      {
       "expr": "avg(node_load15{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 15m"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage",
     "type": "singlestat",
     "description": "-/+ buffers/cache",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"}  - node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"}) / node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"})"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory used"
      },
      {
       "expr": "avg(node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "avg(node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory cached"
      },
      {
       "expr": "avg(node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory free"
      }
     ]
    },
    {
     "title": "K8S Nodes - Disk Space Usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"})"
      }
     ]
    },
    {
     "title": "K8S Nodes - Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "written"
      },
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "io time"
      }
     ]
    },
    {
     "title": "K8S Nodes - Network Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(device) (rate(node_network_receive_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "sum (rate(node_network_receive_bytes_total{ikubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "K8S Nodes - Network Transmitted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(device) (rate(node_network_transmit_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "sum (rate(node_network_transmit_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "K8S Nodes - CPU Usage by Pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\", instance=~\"$K8sNodeInstance\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage by Pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (container_memory_usage_bytes{instance=~\"$K8sNodeInstance\", container!=\"POD\", pod!=\"\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S Nodes - Node - $K8sNodeInstance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8S Nodes - System Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(node_load1{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 1m"
      },
      {
       "expr": "avg(node_load5{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 5m"
      },
      {
       "expr": "avg(node_load15{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "load 15m"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage",
     "type": "singlestat",
     "description": "-/+ buffers/cache",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"}  - node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"}) / node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"})"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(node_memory_MemTotal_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"} - node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory used"
      },
      {
       "expr": "avg(node_memory_Buffers_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "avg(node_memory_Cached_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory cached"
      },
      {
       "expr": "avg(node_memory_MemFree_bytes{kubernetes_node=~\"$K8sNodeInstance\"})",
       "legendFormat": "memory free"
      }
     ]
    },
    {
     "title": "K8S Nodes - Disk Space Usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_node=~\"$K8sNodeInstance\"})"
      }
     ]
    },
    {
     "title": "K8S Nodes - Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "written"
      },
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{kubernetes_node=~\"$K8sNodeInstance\"}[2m]))",
       "legendFormat": "io time"
      }
     ]
    },
    {
     "title": "K8S Nodes - Network Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(device) (rate(node_network_receive_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "sum (rate(node_network_receive_bytes_total{ikubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "K8S Nodes - Network Transmitted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(device) (rate(node_network_transmit_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "sum (rate(node_network_transmit_bytes_total{kubernetes_node=~\"$K8sNodeInstance\",device!~\"lo\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "K8S Nodes - CPU Usage by Pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\", instance=~\"$K8sNodeInstance\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "K8S Nodes - Memory Usage by Pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (container_memory_usage_bytes{instance=~\"$K8sNodeInstance\", container!=\"POD\", pod!=\"\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}